spring:
  application:
    name: portfolio-backend

  # Configurações de produção - segurança habilitada
  security:
    require-ssl: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      org.hibernate.envers.default_schema: portfolio_aud
      hibernate:
        format_sql: false
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        query.in_clause_parameter_padding: true
        default_schema: portfolio

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: portfolio_aud
    liquibase-schema: public
    drop-first: false
    parameters:
      logLevel: INFO

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all
    consumer:
      group-id: portfolio-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: com.jonathanssm.portfoliobackend.model.event.*

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  ssl:
    enabled: false  # SSL é gerenciado pelo nginx

logging:
  level:
    com.jonathanssm.portfoliobackend: ${LOGGING_LEVEL_COM_JONATHANSSM_PORTFOLIOBACKEND:INFO}
    org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:WARN}
    org.hibernate: ${LOGGING_LEVEL_ORG_HIBERNATE:ERROR}
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30

management:
  endpoints.web.exposure.include: health,info,metrics
  endpoint.health.show-details: when-authorized
  endpoint.health.probes.enabled: true
  metrics.export.prometheus.enabled: true
